"""Microsoft Graph API client — minimal wrapper for Outlook mail operations."""
from __future__ import annotations

import html
import re
from dataclasses import dataclass
from typing import Any

import requests

GRAPH_BASE = "https://graph.microsoft.com/v1.0"


@dataclass
class EmailMessage:
    id: str
    subject: str
    sender_name: str
    sender_email: str
    received: str
    body_text: str
    conversation_id: str
    web_link: str


class GraphClient:
    def __init__(self, access_token: str) -> None:
        self._token = access_token
        self._session = requests.Session()
        self._session.headers.update(
            {
                "Authorization": f"Bearer {access_token}",
                "Accept": "application/json",
            }
        )

    def _get(self, path: str, **params: Any) -> dict:
        r = self._session.get(f"{GRAPH_BASE}{path}", params=params, timeout=30)
        r.raise_for_status()
        return r.json()

    def _post(self, path: str, json_body: dict) -> dict:
        r = self._session.post(
            f"{GRAPH_BASE}{path}", json=json_body, timeout=30
        )
        r.raise_for_status()
        # POST /createReply returns the draft message; /reply returns 202 with empty body
        if r.status_code == 202 or not r.content:
            return {}
        return r.json()

    def _patch(self, path: str, json_body: dict) -> dict:
        r = self._session.patch(
            f"{GRAPH_BASE}{path}", json=json_body, timeout=30
        )
        r.raise_for_status()
        if not r.content:
            return {}
        return r.json()

    def list_unread(
        self, folder: str = "Inbox", top: int = 25
    ) -> list[EmailMessage]:
        """List unread messages in a folder, newest first."""
        data = self._get(
            f"/me/mailFolders/{folder}/messages",
            **{
                "$filter": "isRead eq false",
                "$orderby": "receivedDateTime desc",
                "$top": top,
                "$select": (
                    "id,subject,from,receivedDateTime,body,"
                    "bodyPreview,conversationId,webLink"
                ),
            },
        )
        messages = []
        for m in data.get("value", []):
            from_field = (m.get("from") or {}).get("emailAddress") or {}
            body = m.get("body") or {}
            messages.append(
                EmailMessage(
                    id=m["id"],
                    subject=m.get("subject", "") or "(no subject)",
                    sender_name=from_field.get("name", "") or "",
                    sender_email=from_field.get("address", "") or "",
                    received=m.get("receivedDateTime", "") or "",
                    body_text=_strip_html(
                        body.get("content", ""),
                        content_type=body.get("contentType", "text"),
                    ),
                    conversation_id=m.get("conversationId", "") or "",
                    web_link=m.get("webLink", "") or "",
                )
            )
        return messages

    def create_reply_draft(self, message_id: str, reply_body_text: str) -> str:
        """Create a reply draft in Outlook and set its body. Returns draft ID.

        This saves a draft but does NOT send it — the user reviews in Outlook.
        """
        # createReply makes a draft pre-populated with quoted thread + recipients
        draft = self._post(f"/me/messages/{message_id}/createReply", {})
        draft_id = draft["id"]

        # Update body: prepend our proposed reply above the quoted original.
        # Graph returns the draft with the quoted original already in body.content;
        # we prepend the reply text as plain HTML-escaped content.
        original_body = (draft.get("body") or {}).get("content", "")
        escaped = html.escape(reply_body_text).replace("\n", "<br>")
        new_body = (
            f"<div>{escaped}</div>"
            f'<div style="color:#888;font-size:smaller;margin-top:1em;">'
            f"[Draft generated by email_automation — review before sending]</div>"
            f"<hr>{original_body}"
        )
        self._patch(
            f"/me/messages/{draft_id}",
            {"body": {"contentType": "html", "content": new_body}},
        )
        return draft_id


_TAG_RE = re.compile(r"<[^>]+>")
_WS_RE = re.compile(r"[ \t\u00a0]+")
_NL_RE = re.compile(r"\n{3,}")


def _strip_html(content: str, content_type: str = "text") -> str:
    """Convert HTML email body to readable plain text (good enough for the LLM)."""
    if not content:
        return ""
    if content_type.lower() == "text":
        return content.strip()
    # naive but serviceable: drop tags, unescape entities, collapse whitespace
    text = _TAG_RE.sub("\n", content)
    text = html.unescape(text)
    text = _WS_RE.sub(" ", text)
    text = _NL_RE.sub("\n\n", text)
    return text.strip()
